spring.application.name=be
server.port=3001
spring.data.mongodb.uri=mongodb+srv://riyazmittu:F8Wex1urM4bNmHMF@cluster0.7cpwswr.mongodb.net/nexstore?retryWrites=true&w=majority&appName=Cluster0
jwt.secret=OuG4NDUsDx3Iii3gbv7woliz9kLW1KcW3QeQ2tFqkEoG4DqaPvoBozV3pp0TxnTK6DNMHkPyIIAhlKfmEY0Zdw==

# Multipart file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB

api.key=c179e90cba92256e51c73dc9b62a35d3
